Uncover-Commerce/bosie

- sections/announcement-bar.liquid
fix - announcement stylesheet opn and not closed
> refactor: Remove unnecessary span tag in announcement-bar message

- sections/image-banner.liquid
- Removed img_url filter for poster attribute
- Modified video source to use settings.video URL
- Changed video type from 'video' to 'url' in settings
> refactor: Update video source in image-banner component

- assets/template-collection.css
- sections/featured-collection.liquid
- sections/header.liquid
chore: removed nav console logs
> WIP: Add SliderProgress class to control slide progress and navigation buttons

- sections/breadcrumb.liquid
- snippets/breadcrumb.liquid
Fixed class names for better styling consistency in breadcrumb sections.
> style: Update class names in breadcrumb sections

- assets/base.css
> hamburger position

- assets/component-price.css
Changed the color of the regular price to #AB3015 and added comment for
Clarity.
> style: Update color of regular price and add comment

- sections/header.liquid
Reverts Uncover-Commerce/bosie#94 - broke other navigation changes
> Revert "style: Add text capitalization to mega menu columns images"

- sections/main-product.liquid
> fix: Swap units in product page toggle	label

- sections/related-products.liquid
> fix:  missing  carets on slider button - remove hover effect on slider control and change display to block for

- sections/header.liquid
Enhance the list menu in the header section by making it visible
on all screen sizes and adding flex-wrap to ensure items wrap
properly. This improves the overall user experience and layout
of the header menu.
> feat(header): Safari browser fix -  Improve list menu layout and visibility

- assets/base.css
- assets/component-newsletter.css
This pull request includes fixes to the newsletter.
> Fixes to newsletter

- layout/theme.liquid
Fixes #0.
| # | Decision | Alternatives | Rationale | Downsides |
|---|---|---|---|---|
| 1 |   |   |   |   |
- [Store](url)
- [Editor](url)
> Add Klayvio OOS

- layout/theme.liquid
Fixes #0.
| # | Decision | Alternatives | Rationale | Downsides |
|---|---|---|---|---|
| 1 |   |   |   |   |
- [Store](url)
- [Editor](url)
> Add class to Klayvio

- assets/section-main-product.css
Removes the fixed height of the product popup, allowing it to
automatically adjust its size based on the content. This provides a
more natural and responsive user experience when viewing product
details.
> feat: Update product popup sizing

- sections/header.liquid
**PR Description:**
This pull request adds a smooth transition for the `inverted-body` class on the `main` element. When the header is inverted, this change ensures a seamless transition, providing a better user experience for the application.
The commit message details the changes, explaining that the smooth transition is added to the `inverted-body` class on the `main` element. This improvement helps to create a more polished and responsive interface when the header is inverted.
> feat(header): add smooth transition for inverted body

- sections/header.liquid
Refactor the inverted body transition styles to simplify the
implementation and make it more efficient. Remove the unnecessary
transitions on the main element and consolidate the transitions on the
inverted body class. This ensures a smoother and more consistent
transition when the body is inverted.
> feat(header): improve inverted body transition

- assets/component-predictive-search.css
Updates the font-family for the predictive search heading and
adds some spacing to improve the layout and appearance of the
predictive search results.
> feat(predictive-search): update styles for heading

- assets/component-predictive-search.css
Increase top margin for predictive search heading to provide
better visual separation between the heading and the search
results.
> feat: Improve predictive search UX

- sections/header.liquid
Adds event listeners to the header wrapper to invert the navigation
on hover, and remove the inversion when the mouse leaves the header.
This provides a better user experience by automatically inverting the
navigation when the user is interacting with the header.
> feat(navigation): Invert navigation on hover and remove inversion

- sections/header.liquid
This change enhances the navigation inversion functionality in the
header section. The main improvements are:
- Remove the inverted body class from the main content
- Keep the header wrapper class unchanged when reverting the
navigation inversion
- Remove the unnecessary class addition to the header wrapper
Bosie element
These changes provide a more consistent and smoother user
experience when toggling the navigation inversion.
> feat(header): Improve navigation inversion behavior
